package com.novelchat.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFFD4A843)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFF3D6)
val LightSecondary = Color(0xFF8B7355)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFFAFAD2)
val LightOnBackground = Color(0xFF3D3A2E)
val LightSurface = Color(0xFFFFF8DC)
val LightOnSurface = Color(0xFF3D3A2E)
val LightSurfaceVariant = Color(0xFFF5EEC8)
val LightOnSurfaceVariant = Color(0xFF5C5544)
val LightOutline = Color(0xFFC9C0A0)

val DarkPrimary = Color(0xFFF0D060)
val DarkOnPrimary = Color(0xFF3D2E00)
val DarkPrimaryContainer = Color(0xFF5C4400)
val DarkSecondary = Color(0xFFC4A050)
val DarkOnSecondary = Color(0xFF2D2200)
val DarkBackground = Color(0xFF1A1A0E)
val DarkOnBackground = Color(0xFFE8E0C8)
val DarkSurface = Color(0xFF2A2A1A)
val DarkOnSurface = Color(0xFFE8E0C8)
val DarkSurfaceVariant = Color(0xFF3A3A28)
val DarkOnSurfaceVariant = Color(0xFFCAC0A0)
val DarkOutline = Color(0xFF6A6048)

val ErrorColor = Color(0xFFBA1A1A)
val OnErrorColor = Color(0xFFFFFFFF)
val NarratorBg = Color(0x80D4D0B0)
val NarratorText = Color(0xFFFFFFFF)
val HiddenNoteDot = Color(0xFFFF6B35)
